language: node_js
node_js:
  - "0.12"
  - "4.2"
  - "4.3"
  - "4.4"
  - "4.5"
  - "5.5"
  - "5.6"
  - "5.7"
  - "5.8"
  - "5.9"
  - "6.2"

before_script:
  - npm install -g coveralls
  
script:
  - npm run test-cov

after_script:
  - cat ./coverage/lcov.info | coveralls